# Generated by Django 3.2 on 2021-08-09 04:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField(max_length=8)),
                ('address', models.TextField()),
                ('state', models.DateTimeField(default=django.utils.timezone.now)),
                ('vaccinated', models.BooleanField(default=False)),
            ],
        ),
    ]
